language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t sam45564/react-todo-list -f Dockerfile.dev .

script:
  - docker run -e CI=true sam45564/react-todo-list npm run build

after_success:
  - docker build -t sam45564/react-todo-list .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sam45564/react-todo-list
